# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Remblob < Formula
  desc "Edit remote files locally."
  homepage "https://github.com/techiecaro/remblob"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techiecaro/remblob/releases/download/v0.3.2/remblob_0.3.2_darwin_amd64.tar.gz"
      sha256 "7e29d5600beb85d300203e6e40dc21fed9bf76b66ca97af844fa4adab7302139"

      def install
        bin.install "remblob"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techiecaro/remblob/releases/download/v0.3.2/remblob_0.3.2_darwin_arm64.tar.gz"
      sha256 "df360675738ac8cde34bd59a5ff919072b329c04d569aa63f40e2558ee61f22c"

      def install
        bin.install "remblob"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/techiecaro/remblob/releases/download/v0.3.2/remblob_0.3.2_linux_amd64.tar.gz"
      sha256 "2a139037fc86951862ca01bd1fbf6cb8508011ee263ce174fba696b2ff405068"
      def install
        bin.install "remblob"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/techiecaro/remblob/releases/download/v0.3.2/remblob_0.3.2_linux_arm64.tar.gz"
      sha256 "0e147e28faf3891169b7455f0f025218a429f787db494241048d856b394fad9b"
      def install
        bin.install "remblob"
      end
    end
  end
end
