# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Remblob < Formula
  desc "Edit remote files locally."
  homepage "https://github.com/techiecaro/remblob"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/techiecaro/remblob/releases/download/v0.1.0/remblob_0.1.0_Darwin_arm64.tar.gz"
      sha256 "79be80e9e7d0e49a4148eabf6f65b72582c2c8193bd1088a0bd20dee7fe38b7a"

      def install
        bin.install "remblob"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/techiecaro/remblob/releases/download/v0.1.0/remblob_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "c616cbb21e42fcf86fe1664d61dc681eff8f46846116366d69fd841efafafd39"

      def install
        bin.install "remblob"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techiecaro/remblob/releases/download/v0.1.0/remblob_0.1.0_Linux_arm64.tar.gz"
      sha256 "cf34d61baca2a4ad45ced8c051036cd3ebf7ab604289dd8dbf1086abd33c0701"

      def install
        bin.install "remblob"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/techiecaro/remblob/releases/download/v0.1.0/remblob_0.1.0_Linux_x86_64.tar.gz"
      sha256 "69c5605b9171489452b04f4e6003cb0f2a859b6dc50034166f4944efbc9a0dc1"

      def install
        bin.install "remblob"
      end
    end
  end

  depends_on "go" => :optional
end
